- hosts: all
  vars:
    worker_number: 1
    mount_path: /mnt/afs/worker
  become: true
  tasks:
    - name: Install python docker sdk
      pip:
        name: docker
        executable: pip3
      tags:
        - packages

    - name: Create ACI-worker config folder
      file:
        path: "/etc/aciworker"
        state: directory
        mode: '0755'
      tags:
        - configuration

    - name: Copy configs
      copy:
        src: configs/{{ item }}
        dest: /etc/aciworker/{{ item }}
        mode: '0755'
      loop:
        - azure_creds
        - afs_creds.yml
        - env_config
      tags:
        - configuration

    - name: Run docker with codalab-aci-worker
      docker_container:
        name: "aciworker-{{ item }}"
        state: started
        restart: yes
        image: musinov/aci_compute_worker
        volumes:
          - "{{ mount_path }}{{ item }}:/tmp/codalab"
          - /etc/aciworker:/root/.azure
        env_file: /etc/aciworker/env_config
        env:
          AFS_SHARE: "worker{{ item }}"
        network_mode: host
        pull: yes
      with_sequence: count={{ worker_number }}
      tags:
        - deploy