- hosts: all
  vars:
    mount_path: /mnt/afs/worker
  vars_files:
    - workers_list.yml
  become: true
  gather_facts: no
  tasks:
    - name: Install python docker sdk
      pip:
        name: docker
        executable: pip3
      tags:
        - packages

    - name: Create ACI-worker config folder
      file:
        path: "/etc/aciworker"
        state: directory
        mode: '0755'
      tags:
        - configuration

    - name: Copy configs
      copy:
        src: configs/{{ item }}
        dest: /etc/aciworker/{{ item }}
        mode: '0755'
      loop:
        - azure_creds
        - afs_creds.yml
        - stage_env_config
        - prod_env_config
      tags:
        - configuration

    # TODO: make list for worker (stage/dev/prod) & make env for BROKER_URL

    - name: Run docker with codalab-aci-worker
      docker_container:
        name: "aciworker-{{ item.key }}-{{ item.value }}"
        state: started
        restart: yes
        image: musinov/aci_compute_worker
        volumes:
          - "{{ mount_path }}{{ item.key }}:/tmp/codalab"
          - /etc/aciworker:/root/.azure
        env_file: "/etc/aciworker/{{ item.value }}_env_config"
        env:
          AFS_SHARE: "{{ item.key }}"
        network_mode: host
        pull: yes
      loop: "{{ lookup('dict', workers, wantlist=True) }}"
      tags:
        - deploy